# Generated by Django 5.2.4 on 2025-12-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(default=1, upload_to='course_banners/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
