# Generated by Django 5.2.4 on 2026-01-05 11:28

import django.db.models.deletion
from django.db import migrations, models


def copy_question_video(apps, schema_editor):
    Question = apps.get_model('courses', 'Question')
    Test = apps.get_model('courses', 'Test')
    Video = apps.get_model('courses', 'Video')

    for question in Question.objects.all():
        video_id = None
        if question.test_id:
            test = Test.objects.filter(id=question.test_id).first()
            if test and test.video_id:
                video_id = test.video_id
            elif test and test.section_id:
                video = Video.objects.filter(section_id=test.section_id).order_by('created_at', 'id').first()
                if video:
                    video_id = video.id
        if video_id:
            Question.objects.filter(id=question.id).update(video_id=video_id)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_preview_and_test_video'),
        ('course_progress', '0002_remove_test_add_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
        migrations.RunPython(copy_question_video, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='question',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video'),
        ),
    ]
