# Generated by Codex on 2026-01-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_test_add_question_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
