# Generated by Django 5.2.4 on 2026-01-16 10:57

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner_desktop',
            field=models.ImageField(blank=True, null=True, upload_to='course_banners/', validators=[validators.validate_desktop_banner]),
        ),
        migrations.AddField(
            model_name='course',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='course_banners/', validators=[validators.validate_mobile_banner]),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, default='', null=True, upload_to='course_banners/'),
        ),
    ]
